"""Run after changing assets: exact byte sizes for the full-page loading meter."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sizes = {}
for folder in ("assets", "images", "video", "content/newsdrop"):
    for path in (ROOT / folder).rglob("*"):
        if path.is_file() and path.suffix.lower() in {".webp", ".png", ".jpg", ".jpeg", ".svg", ".mp4", ".txt"}:
            # GitHub Pages serves tracked text from the repository's LF blob,
            # while a Windows checkout may expose CRLF in the working tree.
            # Count the bytes that the deployed response contains so the
            # loader cannot reject an otherwise valid News Drop as truncated.
            if path.suffix.lower() == ".txt":
                sizes[path.relative_to(ROOT).as_posix()] = len(path.read_bytes().replace(b"\r\n", b"\n"))
            else:
                sizes[path.relative_to(ROOT).as_posix()] = path.stat().st_size
target = ROOT / "js/core/asset-sizes.js"
target.write_text("// Generated by scripts/build-preload-manifest.py; sizes in bytes.\nexport default " + json.dumps(sizes, sort_keys=True, separators=(",", ":")) + ";\n", encoding="utf-8")
print(f"Manifest: {len(sizes)} files")
